#!/usr/bin/env python3
##!C:\Program Files\Python37\python.exe
import sys
import re
from subprocess import check_output

NUMS_RE = re.compile(r'/[A-Za-z]+-\d{1,}')


def main():
    commit_msg_fn = sys.argv[1]
    lines = [
        line
        for line in open(commit_msg_fn, encoding='utf-8').readlines()
    ]

    current_branch = check_output(
        ['git', 'rev-parse', '--abbrev-ref', 'HEAD']
    ).decode('utf-8')
    story_num_match = NUMS_RE.search(current_branch)
    if not story_num_match:
        return
    story_num = story_num_match.string[
        story_num_match.start():story_num_match.end()
    ]

    if story_num in lines[0]:  # number already there
        return

    lines[0] = '{}: '.format(story_num) + lines[0][:]

    with open(commit_msg_fn, 'w', encoding='utf-8') as commit_file:
        for line in lines:
            commit_file.write(line)


if __name__ == '__main__':
    main()
